version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2022
init:
  - cmd: >-
      set GITVERSION_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%

      if defined APPVEYOR_PULL_REQUEST_NUMBER set GitVersion_NoNormalizeEnabled=true
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
before_build:
  - cmd: >-
      if defined APPVEYOR_PULL_REQUEST_NUMBER git checkout -b PR-%APPVEYOR_PULL_REQUEST_NUMBER%
build:
  project: build/Chorus.proj
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
test: off
artifacts:
- path: output/*nupkg
  name: nuget
deploy:
- provider: Environment
  name: sil-lsdev nuget
notifications:
- provider: GitHubPullRequest
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
