name: Chorus .NET6

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    env:
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      with:
        fetch-depth: 0 # fetch full history for GitVersion
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/sillsdev/index.json
    - name: Fix Python on Linux (for mercurial)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install python-is-python2
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test -c Release
    - name: Pack
      run: dotnet pack --no-restore --no-build -c Release
    - name: Upload Artifacts
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
      with:
        name: chorus-dotnet-nugetpackage
        path: |
          output/*.nupkg
          output/*.snupkg
      if: matrix.os == 'ubuntu-latest'

  publish-nuget:
    name: "Publish NuGet package"
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v3.0.0
      with:
        path: artifacts

    - name: Publish to Nuget
      run: dotnet nuget push artifacts/**/*.*nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.SILLSDEV_PUBLISH_NUGET_ORG}} --skip-duplicate
