name: "Build, Test and Pack"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
      with:
        name: Event File
        path: ${{ github.event_path }}

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      with:
        fetch-depth: 0 # fetch full history for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # v2.1.0
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      # it would be nice to run tests with `--no-build -c Release` but that causes test
      # failures on Ubuntu where it suddenly can't open the display.
      run: dotnet test --filter "FullyQualifiedName=LibChorus.Tests.sync.SyncScenarioTests.CanShareConflictingChangeViaUsb" -- NUnit.TestOutputXml=TestResults

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
      with:
        name: Test Results (${{matrix.os}})
        path: "**/TestResults/*.xml"
