name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.0.2
    - name: Git Fetch
      run: git fetch --unshallow
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build
    - name: Chorus.Tests
      run: dotnet test src/Chorus.Tests/Chorus.Tests.csproj
