name: Chorus .NET6

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build_test_deploy:
    env:
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # fetch full history for GitVersion
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/sillsdev/index.json
    - name: For Mercurial
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install python2
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test
    - name: Pack
      if: github.ref == 'refs/heads/develop'
      run: dotnet pack --no-restore -c Release
    - name: Deploy 1
      if: github.ref == 'refs/heads/develop'
      run: dotnet nuget push output\SIL.Chorus.ChorusMerge**\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.SILLSDEV_PUBLISH_NUGET_ORG}} --skip-duplicate
    - name: Deploy 2
      if: github.ref == 'refs/heads/develop'
      run: dotnet nuget push output\SIL.Chorus.LibChorus.5**\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.SILLSDEV_PUBLISH_NUGET_ORG}} --skip-duplicate
    
